# This is a basic workflow to help you get started with Actions

name: tag build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - dev*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Verison
        id: build_version
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-10-aarch64-linux-gnu
          sudo apt-get install cpio
          sudo mv  /usr/bin/aarch64-linux-gnu-gcc-10  /usr/bin/aarch64-linux-gnu-gcc
      - name: Kernel Build
        run: |
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
      - name: rootfs
        run: |
          curl -LO https://busybox.net/downloads/busybox-1.36.1.tar.bz2
          tar xf busybox-1.36.1.tar.bz2
          cd busybox-1.36.1/
          cp $GITHUB_WORKSPACE/busybox.config.bk .config
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- install
          cd _install/
          find . | cpio -o --format=newc > ../rootfs.img
          cd $GITHUB_WORKSPACE
      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            arch/arm64/boot/Image
            busybox-1.36.1/rootfs.img
          prerelease: ${{ contains(github.ref, '-') }}
